export type Language = "pt-BR" | "en-US" | "es-ES";

type SharedProject = {
  name: string;
  href: string | null;
  caseHref: string | null;
  visualClass: string;
  image: string;
};

const sharedProjects: SharedProject[] = [
  {
    name: "Fabelly",
    href: "https://usefabelly.netlify.app/",
    caseHref: null,
    visualClass: "project-fabelly",
    image: "/images/projects/fabelly-showcase.webp",
  },
  {
    name: "Fabelly Gestor",
    href: "https://fabelly-gestor.netlify.app/",
    caseHref: null,
    visualClass: "project-gestor",
    image: "/images/projects/fabelly-gestor-showcase.webp",
  },
  {
    name: "FoodWave",
    href: "https://victorscape2.gumroad.com/l/foodwave-restaurant-system",
    caseHref: "/projetos/foodwave",
    visualClass: "project-foodwave",
    image: "/images/projects/foodwave-showcase.webp",
  },
  {
    name: "AgendaWave",
    href: "https://agendawave.jvictorsc2018.chatgpt.site",
    caseHref: "/projetos/agendawave",
    visualClass: "project-agendawave",
    image: "/images/projects/agendawave-showcase.webp",
  },
  {
    name: "StockWave",
    href: "https://stockwave.jvictorsc2018.chatgpt.site",
    caseHref: "/projetos/stockwave",
    visualClass: "project-stockwave",
    image: "/images/projects/stockwave-showcase.webp",
  },
  {
    name: "Calmy",
    href: "/calmy",
    caseHref: null,
    visualClass: "project-calma",
    image: "",
  },
];

const sharedProducts = [
  {
    name: "FoodWave Restaurant System",
    href: "https://victorscape2.gumroad.com/l/foodwave-restaurant-system",
    price: "US$ 39",
    visualClass: "product-foodwave",
    image: "/images/projects/foodwave-showcase.webp",
  },
  {
    name: "WhatsApp Product Catalog",
    href: "https://victorscape2.gumroad.com/l/smveks",
    price: "US$ 19",
    visualClass: "product-catalog",
    image: "/images/projects/whatsapp-catalog-showcase.webp",
  },
] as const;

export const siteContent = {
  "pt-BR": {
    meta: {
      title: "João Victor Web | Sites e sistemas sob medida",
      description: "Desenvolvimento de sites, lojas virtuais, cardápios digitais e sistemas de gestão personalizados para empresas.",
    },
    languageLabel: "Selecionar idioma",
    skip: "Ir para o conteúdo",
    brandAria: "João Victor Web — início",
    navAria: "Navegação principal",
    mobileNavAria: "Navegação móvel",
    openMenu: "Abrir menu",
    nav: { services: "Serviços", projects: "Projetos", products: "Produtos", process: "Processo", contact: "Contato" },
    quote: "Orçamento",
    quoteAria: "Solicitar orçamento pelo WhatsApp",
    whatsappMessage: "Olá, João Victor! Vi seu portfólio e gostaria de solicitar um orçamento.",
    hero: {
      eyebrow: "Desenvolvimento web sob medida",
      title: "Sites e sistemas que transformam ideias em",
      emphasis: "negócios.",
      text: "Soluções digitais profissionais para empresas que querem vender, organizar e crescer no digital.",
      quote: "Solicitar orçamento",
      projects: "Ver projetos",
      proofAria: "Diferenciais",
      proofs: ["Design responsivo", "Entrega sob medida", "Suporte próximo"],
      solution: "Soluções digitais que impulsionam",
      result: "resultados",
      projectPanel: "Painel do projeto",
      overview: "Visão geral",
      clients: "Clientes",
      projectsLabel: "Projetos",
      outcome: "Resultado",
      platform: "Plataforma completa",
    },
    services: {
      eyebrow: "Serviços",
      title: "Da primeira ideia à solução funcionando.",
      intro: "Projetos pensados de acordo com a realidade do seu negócio, sem pacotes engessados ou recursos desnecessários.",
      linkLabel: "Ver detalhes",
      detailEyebrow: "Informações do serviço",
      audienceLabel: "Ideal para",
      includesLabel: "O que pode incluir",
      outcomeLabel: "Objetivo",
      cta: "Conversar sobre este serviço",
      whatsappMessage: "Olá, João Victor! Gostaria de saber mais sobre o serviço de",
      items: [
        {
          title: "Sites e landing pages",
          text: "Páginas rápidas, responsivas e pensadas para apresentar sua empresa com profissionalismo e gerar contatos.",
          audience: "Empresas, profissionais autônomos, campanhas e serviços que precisam apresentar uma oferta com clareza e conquistar novos contatos.",
          includes: ["Site institucional ou landing page", "Design adaptado ao celular", "Botões, formulários e WhatsApp", "Publicação e orientação de uso"],
          outcome: "Transmitir confiança, facilitar o contato e transformar visitantes em oportunidades reais para o negócio.",
        },
        {
          title: "Lojas e cardápios digitais",
          text: "Experiências de compra simples, com catálogo, pedidos, pagamento e integração com WhatsApp.",
          audience: "Lojas, restaurantes, delivery e pequenos negócios que desejam apresentar produtos e receber pedidos pela internet.",
          includes: ["Catálogo organizado por categorias", "Carrinho ou fluxo de pedido", "Integração com WhatsApp", "Pagamento e painel administrativo"],
          outcome: "Criar uma jornada de compra simples, rápida e preparada para vender a qualquer hora.",
        },
        {
          title: "Sistemas de gestão",
          text: "Painéis sob medida para organizar produtos, estoque, vendas, clientes, financeiro e relatórios.",
          audience: "Negócios que ainda dependem de planilhas, anotações ou ferramentas desconectadas para controlar a operação.",
          includes: ["Painel administrativo personalizado", "Produtos, estoque e clientes", "Vendas, financeiro e relatórios", "Perfis de acesso e automações"],
          outcome: "Centralizar informações, reduzir trabalho manual e oferecer uma visão clara para tomar decisões.",
        },
        {
          title: "Manutenção e evolução",
          text: "Ajustes, melhorias, integrações e suporte para sua solução continuar acompanhando o negócio.",
          audience: "Empresas que já possuem um site ou sistema e precisam corrigir, atualizar ou ampliar sua solução digital.",
          includes: ["Correções e ajustes de layout", "Novas páginas e funcionalidades", "Integrações com outros serviços", "Acompanhamento e suporte técnico"],
          outcome: "Manter a solução segura, atualizada e alinhada às novas necessidades da empresa.",
        },
      ],
    },
    visual: {
      eyebrow: "Experiências digitais",
      title: "Mais do que páginas: presença, operação e resultado.",
      text: "Cada projeto une direção visual, tecnologia e uma experiência pensada para transformar visitas em ação.",
      tags: ["Web responsiva", "Fluxos inteligentes", "Identidade própria"],
      cta: "Explorar projetos",
      primaryLabel: "Do conceito à solução",
      primaryTitle: "Experiências que apresentam, conectam e vendem.",
      secondaryLabel: "Em qualquer tela",
      secondaryTitle: "Uma presença digital consistente.",
      capabilitiesLabel: "Pilares das experiências digitais",
      capabilities: [
        { title: "Direção visual", text: "Estética alinhada ao seu negócio." },
        { title: "Experiência responsiva", text: "Clareza no celular e no computador." },
        { title: "Solução sob medida", text: "Recursos pensados para a operação real." },
      ],
      studioAlt: "Composição visual de interfaces, painéis e experiências digitais na identidade João Victor Web",
      responsiveAlt: "Computador, tablet e celular apresentando interfaces digitais responsivas",
    },
    projects: {
      eyebrow: "Projetos",
      title: "Soluções criadas para negócios reais.",
      intro: "Uma seleção de experiências digitais que unem apresentação, operação e resultado.",
      items: [
        { ...sharedProjects[0], category: "Loja virtual", description: "Experiência de compra para moda feminina com catálogo, carrinho e pedido direto pelo WhatsApp.", linkLabel: "Visitar projeto" },
        { ...sharedProjects[1], category: "Sistema de gestão", description: "Painel completo para produtos, estoque, pedidos, clientes, vendas, financeiro e relatórios.", linkLabel: "Ver sistema" },
        { ...sharedProjects[2], category: "Produto digital", description: "Cardápio e pedidos online para restaurantes, com pagamentos e visão financeira da operação.", linkLabel: "Conhecer produto" },
        { ...sharedProjects[3], category: "Agendamento e gestão", description: "Plataforma para salões e profissionais organizarem agenda, clientes, serviços, sinal e financeiro.", linkLabel: "Ver plataforma" },
        { ...sharedProjects[4], category: "Estoque e financeiro", description: "Sistema para pequenos comércios controlarem produtos, fornecedores, vendas, caixa e relatórios.", linkLabel: "Ver sistema" },
        { ...sharedProjects[5], category: "Projeto especial em desenvolvimento", description: "Um aplicativo acolhedor inspirado por Camily, criado para apoiar pessoas em momentos de ansiedade com presença e escolhas simples.", linkLabel: "Conhecer o Calmy" },
      ],
    },
    products: {
      eyebrow: "Produtos digitais",
      title: "Soluções prontas para você começar mais rápido.",
      intro: "Compre o produto, receba os arquivos pelo Gumroad e adapte ao seu negócio. Se preferir, também posso cuidar da instalação e da personalização.",
      oneTime: "Pagamento único",
      secure: "Compra segura e entrega pelo Gumroad",
      buy: "Comprar agora",
      buyAria: "Comprar",
      items: [
        {
          ...sharedProducts[0],
          category: "Sistema para restaurantes",
          summary: "Uma base completa para restaurantes venderem online e organizarem a operação em um só lugar.",
          features: ["Cardápio e pedidos online", "Painel financeiro e administrativo", "Português, inglês e espanhol"],
          visualAria: "Prévia do FoodWave com cardápio digital e painel de gestão",
        },
        {
          ...sharedProducts[1],
          category: "Catálogo para vendas",
          summary: "Uma experiência direta para apresentar produtos e transformar visitas em pedidos pelo WhatsApp.",
          features: ["Catálogo organizado", "Pedido direto no WhatsApp", "Layout responsivo"],
          visualAria: "Prévia de um catálogo de produtos conectado ao WhatsApp",
        },
      ],
      customTitle: "Quer receber tudo configurado?",
      customText: "Contrate a instalação, a troca de identidade visual e os ajustes específicos para sua empresa.",
      customButton: "Solicitar personalização",
    },
    process: {
      eyebrow: "Processo",
      title: "Clareza do começo ao lançamento.",
      intro: "Cada etapa é apresentada de forma simples. Antes de qualquer cobrança, você recebe uma proposta com escopo, prazo e valor.",
      link: "Falar sobre meu projeto",
      items: [
        { title: "Conversa inicial", text: "Entendo seu negócio, seu público e o resultado que você espera alcançar." },
        { title: "Proposta e direção", text: "Você recebe o escopo, o prazo, o investimento e a direção visual antes de começarmos." },
        { title: "Criação e acompanhamento", text: "Desenvolvo a solução e compartilho os avanços para validação durante o projeto." },
        { title: "Entrega e suporte", text: "Publico, reviso os detalhes finais e acompanho você nos primeiros passos." },
      ],
    },
    about: {
      eyebrow: "Sobre",
      title: "Tecnologia com conversa simples e atenção aos detalhes.",
      text: "Sou João Victor, desenvolvedor de soluções digitais para pequenos negócios e empresas. Transformo necessidades reais em sites e sistemas fáceis de usar, bonitos e preparados para crescer.",
      tagsAria: "Características do atendimento",
      tags: ["Atendimento direto", "Projeto personalizado", "Entrega digital"],
      atomAria: "Átomo interativo sobre a forma de trabalho de João Victor",
      atomHint: "Clique nos elétrons para explorar",
      nucleus: "Núcleo criativo",
      points: [
        { title: "Visão de negócio", text: "Antes de pensar na tela, entendo o objetivo, o público e o caminho que o visitante precisa percorrer." },
        { title: "Construção sob medida", text: "Design, conteúdo e recursos são organizados para a realidade de cada projeto, sem soluções genéricas." },
        { title: "Evolução contínua", text: "A entrega inclui revisão, orientação e uma base preparada para o produto continuar crescendo." },
      ],
    },
    contact: {
      eyebrow: "Vamos conversar?",
      title: "Sua próxima ideia pode começar agora.",
      text: "Conte brevemente o que você precisa. Responderei pelo WhatsApp para entender o projeto e preparar o próximo passo.",
      button: "Chamar no WhatsApp",
      note: "(86) 99555-0544 • Atendimento online para todo o Brasil",
    },
    business: {
      eyebrow: "Informações comerciais",
      title: "Contratação clara e entrega digital.",
      intro: "João Victor Web presta serviços de desenvolvimento e manutenção de sites e sistemas personalizados. Todo projeto começa com uma proposta que informa o escopo, o prazo, o valor e as condições de pagamento antes da cobrança.",
      tradeName: "Nome comercial",
      owner: "Responsável",
      service: "Atendimento",
      serviceValue: "Online para todo o Brasil",
      contact: "Contato",
      termsTitle: "Termos de contratação",
      terms: [
        "Os serviços incluem criação de sites, lojas e cardápios digitais, sistemas web, integrações, manutenção e suporte. A entrega é digital e segue o escopo e o cronograma aceitos pelo cliente na proposta comercial.",
        "Alterações que não façam parte do escopo original são apresentadas em um novo orçamento antes da execução. Prazos também podem ser ajustados quando o projeto depender do envio de materiais ou aprovações pelo cliente.",
      ],
      cancellationTitle: "Cancelamento e reembolso",
      cancellation: [
        "Pedidos de cancelamento devem ser enviados pelo WhatsApp. Se o desenvolvimento ainda não tiver começado, o valor pago será reembolsado integralmente. Após o início, o reembolso considera as etapas que ainda não foram executadas, conforme o progresso e as condições registradas na proposta aceita.",
        "Eventuais correções relacionadas ao escopo contratado são tratadas durante o período de revisão informado na proposta.",
      ],
      privacyTitle: "Privacidade",
      privacy: [
        "São utilizados somente os dados que o cliente fornece voluntariamente pelo WhatsApp para atendimento, proposta e execução do projeto. Essas informações não são vendidas nem compartilhadas para publicidade de terceiros.",
        "Este site não possui cadastro e não coleta dados de cartão. Quando houver pagamento online, ele será processado em ambiente seguro do provedor de pagamentos apresentado ao cliente.",
      ],
    },
    footer: { legalAria: "Informações legais", terms: "Termos", cancellation: "Cancelamento", privacy: "Privacidade" },
  },
  "en-US": {
    meta: {
      title: "João Victor Web | Custom websites and systems",
      description: "Custom websites, online stores, digital menus and business management systems for companies.",
    },
    languageLabel: "Select language",
    skip: "Skip to content",
    brandAria: "João Victor Web — home",
    navAria: "Main navigation",
    mobileNavAria: "Mobile navigation",
    openMenu: "Open menu",
    nav: { services: "Services", projects: "Projects", products: "Products", process: "Process", contact: "Contact" },
    quote: "Get a quote",
    quoteAria: "Request a quote on WhatsApp",
    whatsappMessage: "Hello, João Victor! I saw your portfolio and would like to request a quote.",
    hero: {
      eyebrow: "Custom web development",
      title: "Websites and systems that turn ideas into",
      emphasis: "business.",
      text: "Professional digital solutions for companies that want to sell, organize and grow online.",
      quote: "Request a quote",
      projects: "View projects",
      proofAria: "Key benefits",
      proofs: ["Responsive design", "Tailored delivery", "Personal support"],
      solution: "Digital solutions that drive",
      result: "results",
      projectPanel: "Project dashboard",
      overview: "Overview",
      clients: "Clients",
      projectsLabel: "Projects",
      outcome: "Results",
      platform: "Complete platform",
    },
    services: {
      eyebrow: "Services",
      title: "From the first idea to a working solution.",
      intro: "Projects designed around the reality of your business, without rigid packages or unnecessary features.",
      linkLabel: "View details",
      detailEyebrow: "Service information",
      audienceLabel: "Best for",
      includesLabel: "What it may include",
      outcomeLabel: "Goal",
      cta: "Discuss this service",
      whatsappMessage: "Hello, João Victor! I would like to learn more about your service:",
      items: [
        {
          title: "Websites and landing pages",
          text: "Fast, responsive pages designed to present your company professionally and generate new leads.",
          audience: "Companies, independent professionals, campaigns and services that need to present an offer clearly and generate new leads.",
          includes: ["Company website or landing page", "Mobile-responsive design", "Buttons, forms and WhatsApp", "Publishing and usage guidance"],
          outcome: "Build trust, make contact easier and turn visitors into genuine business opportunities.",
        },
        {
          title: "Online stores and digital menus",
          text: "Simple shopping experiences with catalogs, ordering, payments and WhatsApp integration.",
          audience: "Stores, restaurants, delivery businesses and small companies that want to showcase products and take orders online.",
          includes: ["Catalog organized by category", "Cart or ordering flow", "WhatsApp integration", "Payments and admin dashboard"],
          outcome: "Create a simple, fast purchasing journey designed to sell at any time.",
        },
        {
          title: "Management systems",
          text: "Custom dashboards for products, inventory, sales, customers, finances and reporting.",
          audience: "Businesses that still rely on spreadsheets, notes or disconnected tools to manage their operations.",
          includes: ["Custom administrative dashboard", "Products, inventory and customers", "Sales, finances and reports", "Access roles and automations"],
          outcome: "Centralize information, reduce manual work and provide a clear view for better decisions.",
        },
        {
          title: "Maintenance and evolution",
          text: "Improvements, integrations and support so your solution keeps pace with your business.",
          audience: "Companies that already have a website or system and need to fix, update or expand their digital solution.",
          includes: ["Corrections and layout updates", "New pages and features", "Third-party integrations", "Ongoing technical support"],
          outcome: "Keep the solution secure, current and aligned with the company’s changing needs.",
        },
      ],
    },
    visual: {
      eyebrow: "Digital experiences",
      title: "More than pages: presence, operations and results.",
      text: "Every project combines visual direction, technology and an experience designed to turn visits into action.",
      tags: ["Responsive web", "Smart workflows", "Distinct identity"],
      cta: "Explore projects",
      primaryLabel: "From concept to solution",
      primaryTitle: "Experiences designed to present, connect and sell.",
      secondaryLabel: "On every screen",
      secondaryTitle: "A consistent digital presence.",
      capabilitiesLabel: "Digital experience pillars",
      capabilities: [
        { title: "Visual direction", text: "A look aligned with your business." },
        { title: "Responsive experience", text: "Clear on mobile and desktop." },
        { title: "Custom solution", text: "Features shaped around real operations." },
      ],
      studioAlt: "A visual composition of interfaces, dashboards and digital experiences in the João Victor Web identity",
      responsiveAlt: "Desktop, tablet and mobile devices displaying responsive digital interfaces",
    },
    projects: {
      eyebrow: "Projects",
      title: "Solutions built for real businesses.",
      intro: "A selection of digital experiences that combine presentation, operations and results.",
      items: [
        { ...sharedProjects[0], category: "Online store", description: "A shopping experience for women's fashion with a catalog, cart and direct ordering through WhatsApp.", linkLabel: "Visit project" },
        { ...sharedProjects[1], category: "Management system", description: "A complete dashboard for products, inventory, orders, customers, sales, finances and reports.", linkLabel: "View system" },
        { ...sharedProjects[2], category: "Digital product", description: "Online menus and ordering for restaurants, with payments and a financial view of operations.", linkLabel: "View product" },
        { ...sharedProjects[3], category: "Scheduling and management", description: "A platform for salons and professionals to manage appointments, customers, services, deposits and finances.", linkLabel: "View platform" },
        { ...sharedProjects[4], category: "Inventory and finance", description: "A system for small retailers to manage products, suppliers, sales, cash flow and reports.", linkLabel: "View system" },
        { ...sharedProjects[5], category: "Special project in development", description: "A welcoming app inspired by Camily, designed to support people through anxiety with presence and simple choices.", linkLabel: "Discover Calmy" },
      ],
    },
    products: {
      eyebrow: "Digital products",
      title: "Ready-made solutions to help you launch faster.",
      intro: "Purchase the product, receive the files through Gumroad and adapt it to your business. If you prefer, I can also handle installation and customization.",
      oneTime: "One-time payment",
      secure: "Secure purchase and delivery through Gumroad",
      buy: "Buy now",
      buyAria: "Buy",
      items: [
        {
          ...sharedProducts[0],
          category: "Restaurant system",
          summary: "A complete foundation for restaurants to sell online and manage their operation in one place.",
          features: ["Online menu and ordering", "Financial and admin dashboard", "Portuguese, English and Spanish"],
          visualAria: "FoodWave preview showing a digital menu and management dashboard",
        },
        {
          ...sharedProducts[1],
          category: "Sales catalog",
          summary: "A direct experience designed to showcase products and turn visits into WhatsApp orders.",
          features: ["Organized product catalog", "Direct WhatsApp ordering", "Responsive layout"],
          visualAria: "Product catalog preview connected to WhatsApp",
        },
      ],
      customTitle: "Would you like everything configured?",
      customText: "Hire me for installation, brand customization and adjustments tailored to your business.",
      customButton: "Request customization",
    },
    process: {
      eyebrow: "Process",
      title: "Clarity from the beginning to launch.",
      intro: "Every step is explained simply. Before any charge, you receive a proposal with the scope, timeline and price.",
      link: "Talk about my project",
      items: [
        { title: "Initial conversation", text: "I learn about your business, your audience and the result you want to achieve." },
        { title: "Proposal and direction", text: "You receive the scope, timeline, investment and visual direction before we begin." },
        { title: "Creation and follow-up", text: "I build the solution and share progress for review throughout the project." },
        { title: "Delivery and support", text: "I publish, review the final details and support you through the first steps." },
      ],
    },
    about: {
      eyebrow: "About",
      title: "Technology explained simply, with attention to detail.",
      text: "I'm João Victor, a developer of digital solutions for small businesses and companies. I turn real needs into websites and systems that are easy to use, polished and ready to grow.",
      tagsAria: "Service characteristics",
      tags: ["Direct communication", "Custom project", "Digital delivery"],
      atomAria: "Interactive atom explaining how João Victor works",
      atomHint: "Click the electrons to explore",
      nucleus: "Creative core",
      points: [
        { title: "Business perspective", text: "Before thinking about the screen, I understand the goal, the audience and the journey each visitor needs to take." },
        { title: "Custom-built solutions", text: "Design, content and features are organized around each project's reality, without generic solutions." },
        { title: "Continuous evolution", text: "Delivery includes review, guidance and a foundation prepared for the product to keep growing." },
      ],
    },
    contact: {
      eyebrow: "Let's talk?",
      title: "Your next idea can start now.",
      text: "Tell me briefly what you need. I'll reply on WhatsApp to understand the project and prepare the next step.",
      button: "Message me on WhatsApp",
      note: "+55 86 99555-0544 • Online service worldwide",
    },
    business: {
      eyebrow: "Business information",
      title: "Clear terms and digital delivery.",
      intro: "João Victor Web provides development and maintenance services for custom websites and systems. Every project begins with a proposal that states the scope, timeline, price and payment terms before any charge.",
      tradeName: "Trade name",
      owner: "Responsible professional",
      service: "Service area",
      serviceValue: "Online service worldwide",
      contact: "Contact",
      termsTitle: "Terms of service",
      terms: [
        "Services include websites, online stores and digital menus, web systems, integrations, maintenance and support. Delivery is digital and follows the scope and schedule accepted by the client in the commercial proposal.",
        "Changes outside the original scope are presented in a new quote before work begins. Timelines may also be adjusted when the project depends on materials or approvals from the client.",
      ],
      cancellationTitle: "Cancellation and refunds",
      cancellation: [
        "Cancellation requests must be sent through WhatsApp. If development has not started, the amount paid will be refunded in full. Once work has begun, the refund covers only the stages not yet completed, based on progress and the terms recorded in the accepted proposal.",
        "Corrections related to the contracted scope are handled during the review period stated in the proposal.",
      ],
      privacyTitle: "Privacy",
      privacy: [
        "Only information voluntarily provided by the client through WhatsApp is used for communication, proposals and project delivery. This information is never sold or shared for third-party advertising.",
        "This website has no user registration and does not collect card details. When online payment is available, it is processed in the secure environment of the payment provider presented to the client.",
      ],
    },
    footer: { legalAria: "Legal information", terms: "Terms", cancellation: "Cancellation", privacy: "Privacy" },
  },
  "es-ES": {
    meta: {
      title: "João Victor Web | Sitios y sistemas a medida",
      description: "Desarrollo a medida de sitios web, tiendas en línea, menús digitales y sistemas de gestión para empresas.",
    },
    languageLabel: "Seleccionar idioma",
    skip: "Ir al contenido",
    brandAria: "João Victor Web — inicio",
    navAria: "Navegación principal",
    mobileNavAria: "Navegación móvil",
    openMenu: "Abrir menú",
    nav: { services: "Servicios", projects: "Proyectos", products: "Productos", process: "Proceso", contact: "Contacto" },
    quote: "Presupuesto",
    quoteAria: "Solicitar presupuesto por WhatsApp",
    whatsappMessage: "¡Hola, João Victor! Vi tu portafolio y me gustaría solicitar un presupuesto.",
    hero: {
      eyebrow: "Desarrollo web a medida",
      title: "Sitios y sistemas que transforman ideas en",
      emphasis: "negocios.",
      text: "Soluciones digitales profesionales para empresas que quieren vender, organizarse y crecer en internet.",
      quote: "Solicitar presupuesto",
      projects: "Ver proyectos",
      proofAria: "Diferenciales",
      proofs: ["Diseño adaptable", "Entrega a medida", "Soporte cercano"],
      solution: "Soluciones digitales que impulsan",
      result: "resultados",
      projectPanel: "Panel del proyecto",
      overview: "Resumen",
      clients: "Clientes",
      projectsLabel: "Proyectos",
      outcome: "Resultado",
      platform: "Plataforma completa",
    },
    services: {
      eyebrow: "Servicios",
      title: "De la primera idea a la solución funcionando.",
      intro: "Proyectos pensados según la realidad de tu negocio, sin paquetes rígidos ni funciones innecesarias.",
      linkLabel: "Ver detalles",
      detailEyebrow: "Información del servicio",
      audienceLabel: "Ideal para",
      includesLabel: "Qué puede incluir",
      outcomeLabel: "Objetivo",
      cta: "Hablar sobre este servicio",
      whatsappMessage: "¡Hola, João Victor! Me gustaría saber más sobre el servicio de",
      items: [
        {
          title: "Sitios y landing pages",
          text: "Páginas rápidas y adaptables, diseñadas para presentar tu empresa profesionalmente y generar contactos.",
          audience: "Empresas, profesionales independientes, campañas y servicios que necesitan presentar una oferta con claridad y conseguir nuevos contactos.",
          includes: ["Sitio institucional o landing page", "Diseño adaptable al móvil", "Botones, formularios y WhatsApp", "Publicación y guía de uso"],
          outcome: "Transmitir confianza, facilitar el contacto y convertir visitantes en oportunidades reales para el negocio.",
        },
        {
          title: "Tiendas y menús digitales",
          text: "Experiencias de compra sencillas con catálogo, pedidos, pagos e integración con WhatsApp.",
          audience: "Tiendas, restaurantes, delivery y pequeños negocios que desean mostrar productos y recibir pedidos por internet.",
          includes: ["Catálogo organizado por categorías", "Carrito o flujo de pedidos", "Integración con WhatsApp", "Pagos y panel administrativo"],
          outcome: "Crear una experiencia de compra sencilla, rápida y preparada para vender a cualquier hora.",
        },
        {
          title: "Sistemas de gestión",
          text: "Paneles a medida para organizar productos, inventario, ventas, clientes, finanzas e informes.",
          audience: "Negocios que todavía dependen de hojas de cálculo, notas o herramientas desconectadas para controlar la operación.",
          includes: ["Panel administrativo personalizado", "Productos, inventario y clientes", "Ventas, finanzas e informes", "Perfiles de acceso y automatizaciones"],
          outcome: "Centralizar la información, reducir el trabajo manual y ofrecer una visión clara para tomar decisiones.",
        },
        {
          title: "Mantenimiento y evolución",
          text: "Mejoras, integraciones y soporte para que tu solución siga el ritmo de tu negocio.",
          audience: "Empresas que ya tienen un sitio o sistema y necesitan corregir, actualizar o ampliar su solución digital.",
          includes: ["Correcciones y ajustes de diseño", "Nuevas páginas y funciones", "Integraciones con otros servicios", "Seguimiento y soporte técnico"],
          outcome: "Mantener la solución segura, actualizada y alineada con las nuevas necesidades de la empresa.",
        },
      ],
    },
    visual: {
      eyebrow: "Experiencias digitales",
      title: "Más que páginas: presencia, operación y resultados.",
      text: "Cada proyecto combina dirección visual, tecnología y una experiencia pensada para transformar visitas en acciones.",
      tags: ["Web adaptable", "Flujos inteligentes", "Identidad propia"],
      cta: "Explorar proyectos",
      primaryLabel: "Del concepto a la solución",
      primaryTitle: "Experiencias para presentar, conectar y vender.",
      secondaryLabel: "En cualquier pantalla",
      secondaryTitle: "Una presencia digital consistente.",
      capabilitiesLabel: "Pilares de las experiencias digitales",
      capabilities: [
        { title: "Dirección visual", text: "Una estética alineada con tu negocio." },
        { title: "Experiencia adaptable", text: "Claridad en móvil y ordenador." },
        { title: "Solución a medida", text: "Recursos pensados para la operación real." },
      ],
      studioAlt: "Composición visual de interfaces, paneles y experiencias digitales con la identidad João Victor Web",
      responsiveAlt: "Ordenador, tableta y móvil mostrando interfaces digitales adaptables",
    },
    projects: {
      eyebrow: "Proyectos",
      title: "Soluciones creadas para negocios reales.",
      intro: "Una selección de experiencias digitales que combinan presentación, operación y resultados.",
      items: [
        { ...sharedProjects[0], category: "Tienda en línea", description: "Experiencia de compra para moda femenina con catálogo, carrito y pedido directo por WhatsApp.", linkLabel: "Visitar proyecto" },
        { ...sharedProjects[1], category: "Sistema de gestión", description: "Panel completo para productos, inventario, pedidos, clientes, ventas, finanzas e informes.", linkLabel: "Ver sistema" },
        { ...sharedProjects[2], category: "Producto digital", description: "Menú y pedidos en línea para restaurantes, con pagos y una visión financiera de la operación.", linkLabel: "Ver producto" },
        { ...sharedProjects[3], category: "Agenda y gestión", description: "Plataforma para que salones y profesionales organicen citas, clientes, servicios, anticipos y finanzas.", linkLabel: "Ver plataforma" },
        { ...sharedProjects[4], category: "Inventario y finanzas", description: "Sistema para que pequeños comercios controlen productos, proveedores, ventas, caja e informes.", linkLabel: "Ver sistema" },
        { ...sharedProjects[5], category: "Proyecto especial en desarrollo", description: "Una aplicación acogedora inspirada por Camily, creada para acompañar la ansiedad con presencia y elecciones sencillas.", linkLabel: "Conocer Calmy" },
      ],
    },
    products: {
      eyebrow: "Productos digitales",
      title: "Soluciones listas para ayudarte a empezar más rápido.",
      intro: "Compra el producto, recibe los archivos a través de Gumroad y adáptalo a tu negocio. Si lo prefieres, también puedo encargarme de la instalación y la personalización.",
      oneTime: "Pago único",
      secure: "Compra segura y entrega a través de Gumroad",
      buy: "Comprar ahora",
      buyAria: "Comprar",
      items: [
        {
          ...sharedProducts[0],
          category: "Sistema para restaurantes",
          summary: "Una base completa para que los restaurantes vendan en línea y organicen su operación en un solo lugar.",
          features: ["Menú y pedidos en línea", "Panel financiero y administrativo", "Portugués, inglés y español"],
          visualAria: "Vista previa de FoodWave con menú digital y panel de gestión",
        },
        {
          ...sharedProducts[1],
          category: "Catálogo para ventas",
          summary: "Una experiencia directa para presentar productos y convertir las visitas en pedidos por WhatsApp.",
          features: ["Catálogo organizado", "Pedido directo por WhatsApp", "Diseño adaptable"],
          visualAria: "Vista previa de un catálogo de productos conectado a WhatsApp",
        },
      ],
      customTitle: "¿Quieres recibirlo todo configurado?",
      customText: "Contrata la instalación, el cambio de identidad visual y los ajustes específicos para tu empresa.",
      customButton: "Solicitar personalización",
    },
    process: {
      eyebrow: "Proceso",
      title: "Claridad desde el comienzo hasta el lanzamiento.",
      intro: "Cada etapa se presenta de forma sencilla. Antes de cualquier cobro, recibes una propuesta con alcance, plazo y precio.",
      link: "Hablar sobre mi proyecto",
      items: [
        { title: "Conversación inicial", text: "Comprendo tu negocio, tu público y el resultado que esperas alcanzar." },
        { title: "Propuesta y dirección", text: "Recibes el alcance, el plazo, la inversión y la dirección visual antes de comenzar." },
        { title: "Creación y seguimiento", text: "Desarrollo la solución y comparto los avances para validarlos durante el proyecto." },
        { title: "Entrega y soporte", text: "Publico, reviso los detalles finales y te acompaño en los primeros pasos." },
      ],
    },
    about: {
      eyebrow: "Sobre mí",
      title: "Tecnología con una conversación sencilla y atención a los detalles.",
      text: "Soy João Victor, desarrollador de soluciones digitales para pequeños negocios y empresas. Transformo necesidades reales en sitios y sistemas fáciles de usar, atractivos y preparados para crecer.",
      tagsAria: "Características de la atención",
      tags: ["Atención directa", "Proyecto personalizado", "Entrega digital"],
      atomAria: "Átomo interactivo sobre la forma de trabajar de João Victor",
      atomHint: "Haz clic en los electrones para explorar",
      nucleus: "Núcleo creativo",
      points: [
        { title: "Visión de negocio", text: "Antes de pensar en la pantalla, comprendo el objetivo, el público y el recorrido que cada visitante debe realizar." },
        { title: "Creación a medida", text: "El diseño, el contenido y las funciones se organizan según la realidad de cada proyecto, sin soluciones genéricas." },
        { title: "Evolución continua", text: "La entrega incluye revisión, orientación y una base preparada para que el producto siga creciendo." },
      ],
    },
    contact: {
      eyebrow: "¿Hablamos?",
      title: "Tu próxima idea puede comenzar ahora.",
      text: "Cuéntame brevemente lo que necesitas. Te responderé por WhatsApp para comprender el proyecto y preparar el siguiente paso.",
      button: "Escribir por WhatsApp",
      note: "+55 86 99555-0544 • Atención en línea internacional",
    },
    business: {
      eyebrow: "Información comercial",
      title: "Contratación clara y entrega digital.",
      intro: "João Victor Web presta servicios de desarrollo y mantenimiento de sitios y sistemas personalizados. Cada proyecto comienza con una propuesta que informa el alcance, el plazo, el precio y las condiciones de pago antes del cobro.",
      tradeName: "Nombre comercial",
      owner: "Responsable",
      service: "Atención",
      serviceValue: "Atención en línea internacional",
      contact: "Contacto",
      termsTitle: "Términos de contratación",
      terms: [
        "Los servicios incluyen la creación de sitios, tiendas y menús digitales, sistemas web, integraciones, mantenimiento y soporte. La entrega es digital y sigue el alcance y el calendario aceptados por el cliente en la propuesta comercial.",
        "Los cambios que no formen parte del alcance original se presentan en un nuevo presupuesto antes de ejecutarse. Los plazos también pueden ajustarse cuando el proyecto dependa del envío de materiales o de aprobaciones del cliente.",
      ],
      cancellationTitle: "Cancelación y reembolso",
      cancellation: [
        "Las solicitudes de cancelación deben enviarse por WhatsApp. Si el desarrollo aún no ha comenzado, el importe pagado se reembolsará íntegramente. Después del inicio, el reembolso contempla las etapas que todavía no se hayan ejecutado, según el progreso y las condiciones registradas en la propuesta aceptada.",
        "Las correcciones relacionadas con el alcance contratado se atienden durante el período de revisión indicado en la propuesta.",
      ],
      privacyTitle: "Privacidad",
      privacy: [
        "Solo se utilizan los datos que el cliente proporciona voluntariamente por WhatsApp para la atención, la propuesta y la ejecución del proyecto. Esta información no se vende ni se comparte para publicidad de terceros.",
        "Este sitio no tiene registro de usuarios ni recopila datos de tarjetas. Cuando exista pago en línea, se procesará en el entorno seguro del proveedor de pagos presentado al cliente.",
      ],
    },
    footer: { legalAria: "Información legal", terms: "Términos", cancellation: "Cancelación", privacy: "Privacidad" },
  },
} as const;

export function detectLanguage(): Language {
  if (typeof window === "undefined") return "pt-BR";
  try {
    const saved = window.localStorage.getItem("joao-victor-web-language");
    if (saved === "pt-BR" || saved === "en-US" || saved === "es-ES") return saved;
  } catch {
    // The browser language remains available when storage is blocked.
  }
  const browserLanguage = window.navigator.language.toLowerCase();
  if (browserLanguage.startsWith("en")) return "en-US";
  if (browserLanguage.startsWith("es")) return "es-ES";
  return "pt-BR";
}
